# Numpy Library

### Numpy library is used to perform Mathematical operations on dataset.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.mean([34,56,7,8,90,12,4,5,7,8])

23.1

In [4]:
np.median([34,56,7,8,90,12,4,5,7,8])

8.0

In [5]:
np.average([34,56,7,8,90,12,4,5,7,8])

23.1

### Dimentions

In [17]:
d_1=[4,8,9,0,5,3,12,56,90]

In [18]:
df=np.array(l1)

In [19]:
df

array([ 4,  8,  9,  0,  5,  3, 12, 56, 90])

In [20]:
df.ndim        # Gives direcrtion of data i.e 1D

1

In [21]:
df_2 = np.array([[7,8,9,5,12],[2,6,8,9,3]])

In [22]:
df_2

array([[ 7,  8,  9,  5, 12],
       [ 2,  6,  8,  9,  3]])

In [23]:
df_2.ndim       #2D array

2

In [24]:
df_3 = np.array([[2,4,6,8,10,12,3],[10,20,70,50,30,20,80],['a','b','c','d','e','f','t']])

In [25]:
df_3

array([['2', '4', '6', '8', '10', '12', '3'],
       ['10', '20', '70', '50', '30', '20', '80'],
       ['a', 'b', 'c', 'd', 'e', 'f', 't']], dtype='<U11')

In [26]:
df_3.ndim

2

In [27]:
d_1

[4, 8, 9, 0, 5, 3, 12, 56, 90]

In [28]:
d_1[0]

4

### Random No. Generation

In [29]:
np.random.randint(1,5,8)   # Gives random integer type of no.

array([2, 2, 4, 2, 3, 3, 1, 4])

In [30]:
np.random.random(10)     # Gives any random 10 no. of float type

array([0.32253869, 0.84968171, 0.32315367, 0.28690197, 0.37740793,
       0.87856563, 0.36419223, 0.41317688, 0.29198942, 0.03630365])

In [32]:
np.random.rand(3,4)   # Creats random no. in 3 rows & 4 columns

array([[0.99798316, 0.12106266, 0.20952818, 0.43770696],
       [0.66559602, 0.90668431, 0.45679402, 0.00564652],
       [0.70198643, 0.28767152, 0.65394172, 0.72508422]])

In [33]:
np.random.rand(2,1)

array([[0.26490479],
       [0.24348575]])

In [35]:
np.random.rand(1,3)

array([[0.46266962, 0.66482852, 0.9180074 ]])